blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

# blog/
urlpatterns = [
    path('', views.blog, name = 'home'),
    path('blog_second', views.blog_second, name = 'blog_second'),
    path('<int:post_id>/', views.post, name = 'post'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

# home/
urlpatterns = [
    path('', views.home, name = 'home'),
]

project_studies/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('home.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from blog.data import posts
from typing import Any
from django.http import Http404

# Create your views here.

def blog(request):
    """
    This function based view is only to test what we learn on the class.
    You can delete it if you want. 
    """
    context = {
        'key': 'database',
        'posts': posts
    }
    
    return render(
        request,
        template_name='blog/index.html',
        context= context
    )

def post(request, post_id):
    """
    This function based view is only to test what we learn on the class.
    You can delete it if you want. 
    """
    found_post: dict[str, Any] | None  = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
    
    if found_post is None:
        raise Http404('Post not found.')

    context = {
        'title': found_post['title'],
        'post': found_post
    }


    return render(
        request,
        template_name='blog/post.html',
        context= context
    )

def blog_second(request):
    """
    This function based view is only to test what we learn on the class.
    You can delete it if you want. 
    """
    return render(
        request,
        template_name='blog/blog_second.html'
    )

home/views.py
from django.shortcuts import render


# Create your views here.

def home(request):
    """
    This function based view is only to test what we learn on the class.
    You can delete it if you want. 
    """
    return render(
        request,
        template_name='home/index.html'
    )

blog/templates/blog/blog_second.html
{% extends "global/base.html" %}

{%block Text %}This page is the second page of blog.{%endblock Text %}

blog/templates/blog/index.html
{% extends "global/base.html" %}

{% block texto %} {{ post.title }} {% endblock texto %}

{% block posts %}
    {% for post in posts %}
        {% include "global/partials/postblock.html"%}
    {% endfor %}
{% endblock posts %}



















# Desconsider this HTML under.
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is our first template on Django.</h1>
    <p>It's the <b>homepage of blog</b>.</p>
</body>
</html>

blog/templates/blog/post.html
{% extends "global/base.html" %}

{% block texto %} {{ post.title }} {% endblock texto %}

{% block posts %}
    <article class="post single-post">

        <head>
            
            <h1 class="post__title">
                <a href= "{% url 'blog:post' post.id %}">
                    {{ post.title}}
                </a>
            </h1>
        </head>

            <div class="post__body">
                {{post.body}}
            </div>

    </article>
{% endblock posts %}



















# Desconsider this HTML under.
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is our first template on Django.</h1>
    <p>It's the <b>homepage of blog</b>.</p>
</body>
</html>

home/templates/home/index.html
{% extends "global/base.html" %}

{%block Text %}This page is the home of pagehome.{%endblock Text %}

{% block home %}
    <h2>
        Home block.
    </h2>
{% endblock home %}